services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - locallens-net

  backend:
    image: raghav3168/locallens-backend:1.1
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - locallens-net

  frontend:
    image: raghav3168/locallens-backend:1.1
    depends_on:
      - backend
    ports:
      - "3000:80"  
    networks:
      - locallens-net

volumes:
  mongo_data:

networks:
  locallens-net:

